apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms_participant_managment-postgresql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: ms_participant_managment-postgresql
  namespace: default
  labels:
    app: ms_participant_managment-postgresql
type: Opaque
data:
  postgresql-password: NDcwOTlkNDQyMTE2MGIwMzFmMzZhZDM5OGJkMDAxZTllYTIyYWM0OWZjMzE0Yjg1MzVlYjY3ZTViNDU5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms_participant_managment-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms_participant_managment-postgresql
  template:
    metadata:
      labels:
        app: ms_participant_managment-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ms_participant_managment-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: ms_participant_managment
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms_participant_managment-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ms_participant_managment-postgresql
  namespace: default
spec:
  selector:
    app: ms_participant_managment-postgresql
  ports:
    - port: 5432
