apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms-participant-managment-app
  namespace: default
  labels:
    team: default
spec:
  selector:
    matchLabels:
      app: ms-participant-managment
  endpoints:
    - port: web
      path: /prometheusMetrics
