apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-participant-managment-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-participant-managment-label
      version: "v1"
  template:
    metadata:
      labels:
        app: ms-participant-managment-label
        version: "v1"
    spec:
      containers:
        - name: ms-participant-managment-app
          image: ECR_REGISTRY/ECR_REPOSITORY:IMAGE_TAG
          env:
            - name: ECR_REGISTRY
              value: $ECR_REGISTRY
            - name: ECR_REPOSITORY
              value: $ECR_REPOSITORY
            - name: IMAGE_TAG
              value: $IMAGE_TAG
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
