apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: myapp
      context: ../myApp
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
